<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Import\Module'                        => __DIR__ . '/Module.php',
    'Import\Controller\ReviewController' => __DIR__ . '/src/Import/Controller/ReviewController.php',
    'ImportTest\Framework\TestCase'        => __DIR__ . '/tests/Import/Framework/TestCase.php',
    'ImportTest\SampleTest'                => __DIR__ . '/tests/Import/SampleTest.php',
);
