<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Upload Reviews') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Make a copy of %sthis import template%s.  Supply with new reviews.  Download as comma-separated values (.csv).  Click Upload and select the file to begin the upload process.'), '<a href="https://goo.gl/TJxrzE" target="_blank">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('import', array()); ?>"><?php echo $this->translate('Upload') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
