<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Upload Reviews') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Make a copy of %sthis import template%s.  Supply with new reviews.  Download as comma-separated values (.csv).  Click Upload and select the file to begin the upload process.'), '<a href="https://goo.gl/yFkAbN" target="_blank">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('import', array()); ?>"><?php echo $this->translate('Upload') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Export Reviews') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Download reviews as .csv file.  You can then import into Google Sheets/Excel to modify the data.  Once complete, you can re-import an updated .csv file.'), '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('export', array()); ?>"><?php echo $this->translate('Download') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Export Default Data') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Download all default data, i.e. action keys, federal agencies, etc. as .xlsx file.'), '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('export-default-data', array()); ?>"><?php echo $this->translate('Download') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
