<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Export\Module'                        => __DIR__ . '/Module.php',
    'Export\Controller\ReviewController' => __DIR__ . '/src/Export/Controller/ReviewController.php',
    'ExportTest\Framework\TestCase'        => __DIR__ . '/tests/Export/Framework/TestCase.php',
    'ExportTest\SampleTest'                => __DIR__ . '/tests/Export/SampleTest.php',
);
